### ISSUE TITLE
There was an unexpected Error. Click to open console for more details.

### ISSUE THREAD

**Issue by Skyfall91** [Kyza/BetterDiscordPlugins#3] opened 2021-11-25 18:21 UTC
It says this when i try to open the settings of the plugin but i cant understand what it says in the console

**Comment by meesam4687** [comment] 2021-12-04 10:10
Cannot read property "icon" of undefined 
Now what

**Comment by Kyza** [comment] 2021-12-06 14:15
Duplicate of https://github.com/Kyza/BetterDiscordPlugins/issues/2.

**Closed as completed by Kyza** 2021-12-06 14:15 UTC
Labels: duplicate
